dj-chat/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('video/', views.play_video, name='video'),
    path('video2/', views.stream_video, name='video2'),

]

dj-chat/dj_chat/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.staticfiles import views
from django.urls import path, re_path
from django.views.generic import TemplateView
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import DefaultRouter

from chat import views as chat_views
from utils.channelsmiddleware import LoginObtainJSONWebToken

router = DefaultRouter()
router.register(r'friends', viewset=chat_views.FriendsViewsets, basename='friends')
router.register(r'chat_log', viewset=chat_views.ChatLogViewsets, basename='chat_log')
router.register(r'personal_chat_log', viewset=chat_views.PersonalChatLogViewsets, basename='personal_chat_log')
router.register(r'chat_room', viewset=chat_views.ChatRoomViewsets, basename='chat_room')
router.register(r'user_profile', viewset=chat_views.UserProfileViewsets, basename='user_profile')
router.register(r'register', viewset=chat_views.RegisterViewsets, basename='register')
router.register(r'talk_log', viewset=chat_views.TalkLogViewsets, basename='talk_log')
router.register(r'user_info', viewset=chat_views.UserInfoViewsets, basename='user_info')
router.register(r'get_statistic', viewset=chat_views.StatisticViewsets, basename='get_statistic')
router.register(r'history', viewset=chat_views.HistoryViewsets, basename='history')

urlpatterns = [
    re_path(r'^chao/', admin.site.urls),
    re_path(r'^admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    re_path('^api/', include(router.urls)),
    re_path(r'^docs/', include_docs_urls(title='API & Dog', description='API文档', public=True)),
    re_path(r'^api-token-auth/', LoginObtainJSONWebToken.as_view()),
    path('', include('chat.urls'), name='chat-url'),
    path('login/', TemplateView.as_view(template_name='login.html'), name='login'),
    path('register/', TemplateView.as_view(template_name='register.html'), name='register'),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
        re_path(r'^src/(?P<path>.*)$', views.serve),
    ]

dj-chat/chat/models.py
from datetime import datetime
from itertools import chain

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from dj_chat.settings import MOREN_TOUXIANG, QUNZU_TOUXIANG


class ChatRoom(models.Model):
    CHAT_TYPE = (
        ('COMMON', '普通类型'),
        ('MUSIC', '音乐类型'),
        ('ROBOT', '机器人回复'),
    )
    room_name = models.CharField(max_length=64, null=False, blank=False, help_text='房间名称')
    room_description = models.CharField(max_length=255, default='这里还没什么描述', help_text='房间描述')
    img_path = models.CharField(max_length=255, default=QUNZU_TOUXIANG, help_text='头像地址')
    channel_no = models.CharField(max_length=8, null=False, blank=False, unique=True, help_text='房间频道号')
    admins = models.ManyToManyField('UserProfile', related_name='chat_admins', help_text='房间管理')
    members = models.ManyToManyField('UserProfile', related_name='chat_member', help_text='房间成员')
    max_number = models.IntegerField(default=5, help_text='允许最大人数')
    ordering = models.IntegerField(default=99, help_text='置顶权')
    chat_type = models.CharField(default='COMMON', choices=CHAT_TYPE, help_text='房间类型', max_length=16)
    date_created = models.DateTimeField(default=datetime.now)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.room_name

    class Meta:
        verbose_name = "聊天室"
        verbose_name_plural = verbose_name

    def get_members_unicode_id(self):
        """
        该房间管理员和成员的uid列表
        :return: list[str]
        """
        member_list = list(self.members.values_list('unicode_id', flat=True))
        admin_list = list(self.admins.values_list('unicode_id', flat=True))
        return member_list + admin_list

    def get_members(self):
        """
        该房间管理员和成员的queryset
        :return: Queryset
        """
        member_list = self.members.all()
        admin_list = self.admins.all()
        return chain(member_list, admin_list)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    nick_name = models.CharField(max_length=64, help_text='昵称')
    signature = models.CharField(max_length=255, null=True, blank=True, help_text='个性签名')
    friends = models.ManyToManyField('self', related_name='my_friends', blank=True)
    unicode_id = models.IntegerField(default=-1, blank=False, null=False, unique=True, help_text='唯一ID')
    img_path = models.CharField(max_length=255, default=MOREN_TOUXIANG, help_text='头像地址')
    city = models.CharField(max_length=64, help_text='城市', null=True, blank=True)
    qq_number = models.CharField(max_length=16, help_text='qq号码', null=True, blank=True)
    is_use_qq_img = models.BooleanField(default=False, help_text='是否使用QQ头像')

    date_created = models.DateTimeField(default=datetime.now)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nick_name + ': ' + str(self.unicode_id)

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name

    def get_img_path(self):
        img_path = self.img_path
        if self.is_use_qq_img and self.qq_number:
            img_path = 'http://q1.qlogo.cn/g?b=qq&nk=%s&s=100' % (self.qq_number)
        elif img_path == '/':
            img_path = MOREN_TOUXIANG
        return img_path

    def get_my_chat_room(self):
        """
        我加入的房间列表
        :return: list[str]
        """
        chat_member = self.chat_member.all().values_list('channel_no', flat=True)
        chat_admins = self.chat_admins.all().values_list('channel_no', flat=True)
        return list(chat_member) + list(chat_admins)


class ChatLog(models.Model):
    chat_datetime = models.DateTimeField(null=True, blank=True, db_index=True, help_text='接收时间')
    content = models.TextField(null=True, blank=True, help_text='聊天内容')
    msg_type = models.CharField(max_length=16, null=True, blank=True, help_text='消息类型')
    who_said = models.ForeignKey(User, on_delete=models.CASCADE, db_constraint=False, related_name='who_said',
                                 help_text='发送者')
    said_to = models.ForeignKey(User, on_delete=models.CASCADE, db_constraint=False, null=True, blank=True,
                                related_name='said_to', help_text='接收者')
    said_to_room = models.ForeignKey(ChatRoom, on_delete=models.CASCADE, db_constraint=False, null=True, blank=True,
                                     related_name='said_to_room', help_text='接收房间')
    said_together = models.CharField(max_length=64, null=True, blank=True)
    status = models.CharField(max_length=16, default='read', help_text='消息状态')

    class Meta:
        verbose_name = "聊天记录"
        verbose_name_plural = verbose_name


class TalkLog(models.Model):
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, db_constraint=False, related_name='talk_log',
                                help_text='说说')
    content = models.TextField(null=True, blank=True, help_text='说说内容')
    star = models.IntegerField(default=0)
    reading = models.IntegerField(default=0)
    date_created = models.DateTimeField(default=datetime.now)
    date_modified = models.DateTimeField(auto_now=True)


class History(models.Model):
    ip = models.CharField(max_length=64, null=True, blank=True)
    city = models.CharField(max_length=64, null=True, blank=True)
    device = models.CharField(max_length=64, null=True, blank=True)
    count = models.IntegerField(default=0)
    date_created = models.DateTimeField(default=datetime.now)

dj-chat/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="Django Websocket 在线多人聊天室">
    <meta name="description" content="Django Websocket 在线多人聊天室 支持单对单,多对多聊天，消息通知,发布talks功能">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Charles</title>

    <!-- Bootstrap -->

    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon"/>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon"/>
    <!-- Theme style -->

    <link rel="stylesheet" href="{% static 'css/AdminLTE.min.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/_all-skins.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/xtiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/xui.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'css/Lobibox.min.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>

    <![endif]-->
</head>
{% block css %} {% endblock %}

<body>
{% block body %} {% endblock %}
</body>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/xtiper.min.js' %}"></script>
<script src="{% static 'js/lobibox.min.js' %}"></script>
<script src="{% static 'js/notifications.min.js' %}"></script>
<script src="{% static 'js/re-websocket.min.js' %}"></script>

<script>
    // 防抖
    function debouce(func, delay, immediate) {
        var timer = null;
        return function () {
            var context = this;
            var args = arguments;
            if (timer) clearTimeout(timer);
            if (immediate) {
                //根据距离上次触发操作的时间是否到达delay来决定是否要现在执行函数
                var doNow = !timer;
                //每一次都重新设置timer，就是要保证每一次执行的至少delay秒后才可以执行
                timer = setTimeout(function () {
                    timer = null;
                }, delay);
                //立即执行
                if (doNow) {
                    func.apply(context, args);
                }
            } else {
                timer = setTimeout(function () {
                    func.apply(context, args);
                }, delay);
            }
        }
    }

    String.prototype.format = function () {
        //将arguments转化为数组（ES5中并非严格的数组）
        var args = Array.prototype.slice.call(arguments);
        var count = 0;
        //通过正则替换%s
        return this.replace(/%s/g, function (s, i) {
            return args[count++];
        });
    };
    $.ajaxSetup({
        dataType: "json",
        cache: false,
        headers: {
            "X-CSRFToken": "{{ csrf_token }}",
            'Authorization': 'Jwt ' + window.localStorage.token
        },
        xhrFields: {
            withCredentials: true
        },
        complete: function (data) {
            //token过期，则跳转到登录页面
            if (data.status === 401) {
                window.location.href = '/login/'
            }
        }
    });

</script>
{% block script %} {% endblock %}
</html>

dj-chat/templates/login.html
{% extends "base.html" %}

{% block body %}
  <body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a href="#"><b>Charles</b>LTE</a>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg">测试账号：admin 密码: xhongc</p>

      <form action="/api-token-auth/" method="post">
        <div class="form-group has-feedback">
          <input type="text" class="form-control" placeholder="Username" id="id_username">
          <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input type="password" class="form-control" placeholder="Password" id="id_password">
          <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox">
              <label>
                <input type="checkbox" checked> 记住我
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat" id="id_submit">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>


{#      <a href="#">I forgot my password</a><br>#}
      <a href="/register" class="text-center">-注册-</a>

    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->


  </body>
{% endblock %}
{% block script %}
  <script>
      function logIn() {
          var username = $('#id_username').val();
          var password = $('#id_password').val();
          $.ajax({
              url: '/api-token-auth/',
              type: 'post',
              headers: {
                  "X-CSRFToken": "{{ csrf_token }}"
              },
              data: {'username': username, 'password': password},
              success: function (data) {
                  localStorage.setItem('token',data.token);
                  localStorage.setItem('user_id',data.user_id);
                  window.location.href = '/'
              },
              error: function (data) {
                  xtip.msg(data.statusText);
              }

          })
      }

      $('#id_submit').click(function (e) {
          e.preventDefault();
          logIn();
      })
  </script>
{% endblock %}

dj-chat/templates/register.html
{% extends "base.html" %}
{% load staticfiles %}

{% block body %}
    <body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a href="/"><b>Charles</b>LTE</a>
        </div>
        <div class="register-box-body">
            <p class="login-box-msg">账号·注册</p>

            <form method="post" id="register_form">
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="中文昵称" id="id_nick_name">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="text" class="form-control" placeholder="账号" id="id_username">
                    <span class="glyphicon glyphicon-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="email" class="form-control" placeholder="QQ邮箱" id="id_email">
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="密码" id="id_password">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" placeholder="确认·密码" id="id_password2">
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="checkbox icheck">
                            <label>
                                <input type="checkbox" checked> 我已经同意 <a href="#">入坑</a>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="button" class="btn btn-primary btn-block btn-flat" id="id_submit">注册</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign
                    up using
                    Facebook</a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign
                    up using
                    Google+</a>
            </div>

            <a href="/login" class="text-center">我已经有账号</a>
        </div>
        <!-- /.form-box -->
    </div>
    <!-- /.register-box -->
    </body>
{% endblock %}
{% block script %}
    <script>
        function register() {
            $.ajax({
                url: '/api/register/',
                type: 'post',
                headers: {
                    "X-CSRFToken": "{{ csrf_token }}"
                },
                data: {
                    'nick_name': $('#id_nick_name').val(),
                    'username': $('#id_username').val(),
                    'email': $('#id_email').val(),
                    'password': $('#id_password').val(),
                    'password2': $('#id_password2').val(),
                },
                success: function (data) {
                    window.location.href = '/login'
                    xtip.msg('注册成功')
                },
                error: function (data) {
                    xtip.msg(data.responseText);
                }

            })
        }
        let elem = document.getElementById('id_submit');
        elem.addEventListener('click', debouce(register, 1000, true));
    </script>
{% endblock %}